charlas/django/codigo/newblog/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^newblog/', include('newblog.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^agregar/$', 'newblog.posts.views.agregar_post'),
    (r'^$', 'newblog.posts.views.index'),

)

charlas/django/codigo/newblog/posts/models.py
from django.db import models

class Post(models.Model):
    titulo = models.CharField(max_length=50)
    contenido = models.TextField()
    etiquetas = models.ManyToManyField('Etiqueta')

    def __unicode__(self):
        return self.titulo

class Etiqueta(models.Model):
    nombre = models.CharField(max_length=25)

    def __unicode__(self):
        return self.nombre

class Comentario(models.Model):
    autor = models.CharField(max_length=25)
    contenido = models.TextField()
    post = models.ForeignKey(Post)

charlas/django/codigo/newblog/posts/forms.py
from django.forms import ModelForm
from fmlatribu.posts.models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post

charlas/django/codigo/newblog/posts/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from newblog.posts.forms import PostForm
from newblog.posts.models import Post

def agregar_post(request):
    if request.method == 'GET':
        formulario = PostForm()
        return render_to_response('posts/agregar_post.html',
                                 {'formulario': formulario})
    else:
        formulario = PostForm(request.POST)
        if formulario.is_valid():
            formulario.save()
        return HttpResponseRedirect('/')

def index(request):
    posts = Post.objects.all()

    return render_to_response('index.html',
                              {'posts': posts,
                               'variable': 'una cadena'})

charlas/django/codigo/newblog/posts/templates/posts/agregar_post.html
{% extends "base.html" %}

{% block content %}
<form method="post" action=".">
<table>
{{ formulario.as_table }}
</table>
<input type="submit" value="Enviar" />
</form>
{% endblock %}

charlas/django/codigo/newblog/templates/base.html
<html>
<header>
<title>Charla de Django</title>
</header>

<body>
<h1>Bienvenidos!</h1>
{% block content %}
{% endblock %}
</body>

</html>

charlas/django/codigo/newblog/templates/index.html
{% extends "base.html" %}
{% load posts_extras %}

{% block content %}

{% for post in posts %}
<div>
<h2>{{ post.titulo }}</h2>
<p>{{ post.contenido }}</p>
{% for comentario in post.comentario_set.all %}
<li>autor: {{ comentario.autor }}
<p>{{ comentario.contenido }}</p>
</li>
{% endfor %}
</div>
{% endfor %}

Prueba del templatetag (filtro) que definimos: escribo {{ variable|sayhello|lower }}

{% endblock %}